/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_java;

import controller.controlPersonne;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROG
 */
public class corbeille extends javax.swing.JInternalFrame {

    /**
     * Creates new form corbeille
     */
    public corbeille() {
        initComponents();
        ChargerListe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delet_contain = new javax.swing.JScrollPane();
        list_deleted = new javax.swing.JTable();
        restore_btn = new javax.swing.JToggleButton();
        delet_btn = new javax.swing.JButton();
        empty_trash = new javax.swing.JButton();

        setBorder(null);

        list_deleted.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        delet_contain.setViewportView(list_deleted);

        restore_btn.setBackground(new java.awt.Color(0, 153, 204));
        restore_btn.setForeground(new java.awt.Color(255, 255, 255));
        restore_btn.setText("Restaurer");
        restore_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restore_btnActionPerformed(evt);
            }
        });

        delet_btn.setBackground(new java.awt.Color(255, 0, 0));
        delet_btn.setForeground(new java.awt.Color(255, 255, 255));
        delet_btn.setText("Supprimer");
        delet_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_btnActionPerformed(evt);
            }
        });

        empty_trash.setBackground(new java.awt.Color(255, 0, 0));
        empty_trash.setForeground(new java.awt.Color(255, 255, 255));
        empty_trash.setText("Vider la corbeille");
        empty_trash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empty_trashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(delet_contain, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restore_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delet_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empty_trash, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(delet_contain, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restore_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empty_trash, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delet_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_btnActionPerformed
        
        int ligne = list_deleted.getSelectedRow();
        String clientId = String.valueOf(list_deleted.getValueAt(ligne, 0));
        System.out.println("client id : " + clientId);
        if (clientId==null){
            JOptionPane.showMessageDialog(this, "Veuillez choisir un svp");
        }
        else{
            int response = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer ce personnel ?", "Supprimer definitivement", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response==JOptionPane.YES_OPTION){
                try {
                    controlPersonne cp = new controlPersonne();
                    cp.delete(clientId);
                    ChargerListe();

                } catch (Exception ex) {
                    Logger.getLogger(corbeille.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        }
    }//GEN-LAST:event_delet_btnActionPerformed

    private void restore_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restore_btnActionPerformed
        int ligne = list_deleted.getSelectedRow();
        String clientId = String.valueOf(list_deleted.getValueAt(ligne, 0));
        try {
            controlPersonne cp = new controlPersonne();
            cp.restore(clientId);
            ChargerListe();
            JOptionPane.showMessageDialog(this, "Restoration avec succes !");
        } catch (Exception ex) {
            Logger.getLogger(corbeille.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_restore_btnActionPerformed

    private void empty_trashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empty_trashActionPerformed
       int response = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment vider la corbeille ?", "Supprimer tout definitivement", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response==JOptionPane.YES_OPTION){
                try {
                    controlPersonne cp = new controlPersonne();
                    cp.videCorbeille();
                    ChargerListe();
                    
                } catch (Exception ex) {
                    Logger.getLogger(corbeille.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
    }//GEN-LAST:event_empty_trashActionPerformed

// fucntion to charge all liste of personnal
    public void ChargerListe() {
        String titre[] = {"id", "Nom", "Prénoms","Date de naissance","Adresse", "Numero de telephone", "CIN"};
        Object enreg[][] = new Object[1][1];

        try {
            controlPersonne cp = new controlPersonne();
            int nbr = cp.countEnreg();
            enreg = new Object[nbr][titre.length];
            ResultSet rs1 = cp.getAllDel();
            int i = 0;
            while (rs1.next()) {
                enreg[i][0] = (Object) rs1.getString("id");
                enreg[i][1] = (Object) rs1.getString("nom");
                enreg[i][2] = (Object) rs1.getString("prenom");
                enreg[i][3] = (Object) rs1.getString("Date_naissance");
                enreg[i][4] = (Object) rs1.getString("adresse");
                enreg[i][5] = (Object) rs1.getString("num_tel");
                enreg[i][6] = (Object) rs1.getString("Num_cin");
                i++;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        list_deleted.setModel(new DefaultTableModel(enreg, titre));
        delet_contain.setViewportView(list_deleted);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delet_btn;
    private javax.swing.JScrollPane delet_contain;
    private javax.swing.JButton empty_trash;
    private javax.swing.JTable list_deleted;
    private javax.swing.JToggleButton restore_btn;
    // End of variables declaration//GEN-END:variables
}
