/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_java;

import controller.loginControl;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ROG
 */
public class parametre extends javax.swing.JInternalFrame {

    boolean securised;
    public parametre() throws Exception {
        initComponents();
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        chargeFrom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        secure_contain = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        input_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        input_mdp = new javax.swing.JTextField();

        setBorder(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PARAMETRE");

        secure_contain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/secure.png"))); // NOI18N
        jLabel3.setText("Securiser");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout secure_containLayout = new javax.swing.GroupLayout(secure_contain);
        secure_contain.setLayout(secure_containLayout);
        secure_containLayout.setHorizontalGroup(
            secure_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secure_containLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        secure_containLayout.setVerticalGroup(
            secure_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secure_containLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Nom d'utilisateur: ");

        save_btn.setBackground(new java.awt.Color(0, 153, 204));
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setText("Enregistrer");
        save_btn.setBorder(null);
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Mot de passe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secure_contain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_name)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(input_mdp))))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(secure_contain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        if (securised == false){
            securised = true;
            secure_contain.setBackground(Color.decode("#33FFFF"));
            input_name.setEnabled(true);
            input_mdp.setEnabled(true);
            save_btn.setEnabled(true);
        }
        else{
            securised = false;
            secure_contain.setBackground(Color.decode("#FFFFFF"));
            input_name.setEnabled(false);
            input_mdp.setEnabled(false);
            save_btn.setEnabled(false);
        }
        try {
            loginControl lgc = new loginControl();
            lgc.changeParameter(securised);
        } catch (Exception ex) {
            Logger.getLogger(parametre.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        String nom = input_name.getText();
        String mdp = input_mdp.getText();
        try {
            loginControl lg = new loginControl();
            lg.changeAuth(nom, mdp);
            JOptionPane.showMessageDialog(this, "Modification effectueravec succes !");
        } catch (Exception ex) {
            Logger.getLogger(parametre.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_save_btnActionPerformed
    
    public void chargeFrom() throws Exception{
        loginControl lg = new loginControl();
        securised = lg.secureOrNo();
        System.out.println(securised);
        System.out.println(securised);
        if (securised == false){
            secure_contain.setBackground(Color.decode("#ffffff"));
            input_name.setEnabled(false);
            input_mdp.setEnabled(false);
            save_btn.setEnabled(false);
        }
        else{
            secure_contain.setBackground(Color.decode("#33FFFF"));
            input_name.setEnabled(true);
            input_mdp.setEnabled(true);
            save_btn.setEnabled(true);
        }
        String userData[] = lg.secureData();
        input_name.setText(userData[0]);
        input_mdp.setText(userData[1]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_mdp;
    private javax.swing.JTextField input_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton save_btn;
    private javax.swing.JPanel secure_contain;
    // End of variables declaration//GEN-END:variables
}
