/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_java;

import controller.controlPersonne;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROG
 */
public class personnel_views extends javax.swing.JInternalFrame {

    /**
     * Creates new form personnel_views
     */
    public personnel_views() {
        initComponents();
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        edit_button.setEnabled(false);
        chargerListe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        list_employe = new javax.swing.JScrollPane();
        list_result = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        personnel_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        info_contain = new javax.swing.JPanel();
        qr_contain = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        prename = new javax.swing.JLabel();
        sexe = new javax.swing.JLabel();
        date_naiss = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cin = new javax.swing.JLabel();
        poste = new javax.swing.JLabel();
        edit_button = new javax.swing.JButton();
        del_btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(240, 242, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        list_employe.setBackground(new java.awt.Color(255, 255, 255));
        list_employe.setBorder(null);

        list_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        list_result.setGridColor(new java.awt.Color(255, 255, 255));
        list_result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_resultMouseClicked(evt);
            }
        });
        list_employe.setViewportView(list_result);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(list_employe, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(list_employe, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        personnel_search.setForeground(new java.awt.Color(102, 102, 102));
        personnel_search.setText("cherche ici...");
        personnel_search.setBorder(null);
        personnel_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                personnel_searchKeyTyped(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personnel_search, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(personnel_search, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        add_button.setBackground(new java.awt.Color(0, 153, 255));
        add_button.setForeground(new java.awt.Color(255, 255, 255));
        add_button.setText("+ Ajouter employe");
        add_button.setBorder(null);
        add_button.setBorderPainted(false);
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        info_contain.setBackground(new java.awt.Color(255, 255, 255));
        info_contain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        qr_contain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qr_contain.setText("QR CODE PERSONNEL");

        jLabel2.setText("Nom : ");

        jLabel3.setText("Prenom : ");

        jLabel4.setText("Date de naissance : ");

        jLabel5.setText("Adresse : ");

        jLabel6.setText("Numero CIN : ");

        jLabel7.setText("Poste : ");

        jLabel8.setText("Sexe : ");

        name.setText("Nom complet");

        prename.setText("Prenom_complet");

        sexe.setText("Homme ou Femme");

        date_naiss.setText("0000-00-00");

        jLabel9.setText("Adresse");

        cin.setText("000 000 000 000");

        poste.setText("Poste");

        javax.swing.GroupLayout info_containLayout = new javax.swing.GroupLayout(info_contain);
        info_contain.setLayout(info_containLayout);
        info_containLayout.setHorizontalGroup(
            info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_containLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qr_contain, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(info_containLayout.createSequentialGroup()
                        .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(71, 71, 71)
                        .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexe)
                            .addComponent(prename)
                            .addComponent(name)))
                    .addGroup(info_containLayout.createSequentialGroup()
                        .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poste)
                            .addComponent(cin)
                            .addComponent(jLabel9)
                            .addComponent(date_naiss))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        info_containLayout.setVerticalGroup(
            info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_containLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prename))
                .addGap(12, 12, 12)
                .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sexe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(date_naiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(info_containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(poste))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qr_contain, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        edit_button.setBackground(new java.awt.Color(0, 204, 0));
        edit_button.setForeground(new java.awt.Color(255, 255, 255));
        edit_button.setText("Modifier");
        edit_button.setBorder(null);
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });

        del_btn.setBackground(new java.awt.Color(255, 0, 0));
        del_btn.setForeground(new java.awt.Color(255, 255, 255));
        del_btn.setText("Supprimer");
        del_btn.setBorder(null);
        del_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btnActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));

        jLabel10.setBackground(new java.awt.Color(0, 51, 102));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print.png"))); // NOI18N
        jLabel10.setText("Imprimer le carte");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(info_contain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(del_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(del_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addComponent(info_contain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personnel_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personnel_searchKeyTyped
        String txtContent = personnel_search.getText();
        if ("cherche ici...".equals(txtContent)){
            personnel_search.setText("");
            personnel_search.setForeground(Color.BLACK);
        }
        if ("".equals(txtContent)){
            personnel_search.setText("cherche ici...");
            personnel_search.setForeground(Color.decode("#666666"));
        }
    }//GEN-LAST:event_personnel_searchKeyTyped

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        modal_personnel addPers = new modal_personnel();
        addPers.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        addPers.setVisible(true);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void list_resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_resultMouseClicked
        edit_button.setEnabled(true);
        int ligne = list_result.getSelectedRow();
        String clientId = String.valueOf(list_result.getValueAt(ligne, 0));
        
        try {
            controlPersonne cp = new controlPersonne();
            String client[] = cp.getPersonnal(clientId);
            
            name.setText(client[1]);
            prename.setText(client[2]);
            date_naiss.setText(client[3]);
            String sexValeur = client[6].split("")[5];
            if (sexValeur.equals("1")) sexe.setText("Homme");
            else sexe.setText("Femme");
            poste.setText(client[4]);
            cin.setText(client[6]);
            
            qr_contain.setText("");
            ImageIcon qrcode = ResizeQR(client[8]);
            System.out.println(qrcode);
            qr_contain.setIcon(qrcode);
        } catch (Exception ex) {
            Logger.getLogger(personnel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_list_resultMouseClicked

    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
        int ligne = list_result.getSelectedRow();
        String clientId = String.valueOf(list_result.getValueAt(ligne, 0));
        
        try {
            controlPersonne cp = new controlPersonne();
            String client[] = cp.getPersonnal(clientId);
            // Set value of all Champs
            modal_personnel editPers = new modal_personnel();
            editPers.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            editPers.setVisible(true);
            
            editPers.fillValues(client[0], client[1],client[2], client[6], client[7], client[3], client[5], client[4]);
            editPers.modifActive();

        } catch (Exception ex) {
            Logger.getLogger(personnel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_edit_buttonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        String searchValue = personnel_search.getText();
        if (searchValue.equals("cherche ici...") || searchValue.equals("") || searchValue==null) chargerListe();
        else searchListe(searchValue);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void del_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btnActionPerformed
        int ligne = list_result.getSelectedRow();
        String clientId = String.valueOf(list_result.getValueAt(ligne, 0));
        try {
            controlPersonne cp = new controlPersonne();
            cp.virtualDelete(clientId);
            chargerListe();
            JOptionPane.showMessageDialog(this, "Deplace dans corbeille!");
        } catch (Exception ex) {
            Logger.getLogger(personnel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_del_btnActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        card_member crt = new card_member();
        int ligne = list_result.getSelectedRow();
        String clientId = String.valueOf(list_result.getValueAt(ligne, 0));
        try {
            controlPersonne cp = new controlPersonne();
            String client[] = cp.getPersonnal(clientId);
            
            crt.addValue(client[1], client[2], client[6], client[7], client[4], client[8],client[9]);
            crt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            crt.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(personnel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jLabel10MouseClicked

    
    //fonction control des valeur dans le champs
    public void chargerListe() {
        String titre[] = {"id", "Nom", "Prénoms", "Adresse"};
        Object enreg[][] = new Object[1][1];

        try {
            controlPersonne cp = new controlPersonne();
            
            int nbr = cp.countEnreg();
            enreg = new Object[nbr][titre.length];
            ResultSet rs1 = cp.getAll();
            int i = 0;
            while (rs1.next()) {
                enreg[i][0] = (Object) rs1.getString("id");
                enreg[i][1] = (Object) rs1.getString("nom");
                enreg[i][2] = (Object) rs1.getString("prenom");
                enreg[i][3] = (Object) rs1.getString("adresse");
                i++;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        list_result.setModel(new DefaultTableModel(enreg, titre));
        list_employe.setViewportView(list_result);
    }
    public void searchListe(String str) {
        String titre[] = {"id", "Nom", "Prénoms", "Adresse"};
        Object enreg[][] = new Object[1][1];

        try {
            controlPersonne cp = new controlPersonne();
            
            int nbr = cp.countEnreg();
            enreg = new Object[nbr][titre.length];
            ResultSet rs1 = cp.searchAll(str);
            int i = 0;
            while (rs1.next()) {
                enreg[i][0] = (Object) rs1.getString("id");
                enreg[i][1] = (Object) rs1.getString("nom");
                enreg[i][2] = (Object) rs1.getString("prenom");
                enreg[i][3] = (Object) rs1.getString("adresse");
                i++;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        list_result.setModel(new DefaultTableModel(enreg, titre));
        list_employe.setViewportView(list_result);
    }
    public ImageIcon ResizeQR(String imagePath){
        ImageIcon myImage = new javax.swing.ImageIcon(getClass().getResource(imagePath));
        Image imge = myImage.getImage();
        Image newImage = imge.getScaledInstance(qr_contain.getWidth(), qr_contain.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    
    //Fonctionalite scanner
    public static void printer(JPanel pan){
        PrinterJob prnt = PrinterJob.getPrinterJob();
        prnt.setJobName("Imprsession de carte personnel");
        prnt.setPrintable(new Printable(){
            @Override
            public int print(Graphics grphcs, PageFormat pf, int i) throws PrinterException {
                if(i>0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D grph = (Graphics2D)grphcs;
                grph.translate(pf.getImageableX()*2, pf.getImageableY()*2);
                grph.scale(0.5, 0.5);
                
                pan.paint(grph);
                return Printable.PAGE_EXISTS;
            }
            
        });
        boolean result = prnt.printDialog();
        if(result){
            try{
                prnt.print();
            }
            catch(PrinterException printerException){
                System.out.println("Erreur d'impression");
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel cin;
    private javax.swing.JLabel date_naiss;
    private javax.swing.JButton del_btn;
    private javax.swing.JButton edit_button;
    private javax.swing.JPanel info_contain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane list_employe;
    private javax.swing.JTable list_result;
    private javax.swing.JLabel name;
    private javax.swing.JTextField personnel_search;
    private javax.swing.JLabel poste;
    private javax.swing.JLabel prename;
    private javax.swing.JLabel qr_contain;
    private javax.swing.JLabel sexe;
    // End of variables declaration//GEN-END:variables
}
