/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_java;

import controller.Personne;
import controller.controlPersonne;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author ROG
 */
public class personnel extends javax.swing.JInternalFrame {

    /**
     * Creates new form personnel
     */
    public personnel() {
        initComponents();
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        identifiant.setVisible(false);
        
        ChargerListe();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        liste_employe = new javax.swing.JScrollPane();
        liste_result = new javax.swing.JTable();
        client_search = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        poste = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        photoImage = new javax.swing.JLabel();
        qrcontain = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        adresse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        date_naissance = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        add_image = new javax.swing.JButton();
        identifiant = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        liste_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        liste_result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liste_resultMouseClicked(evt);
            }
        });
        liste_employe.setViewportView(liste_result);

        client_search.setBackground(new java.awt.Color(204, 204, 204));
        client_search.setForeground(new java.awt.Color(102, 102, 102));
        client_search.setText("cherche ici...");
        client_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_searchActionPerformed(evt);
            }
        });
        client_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                client_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                client_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                client_searchKeyTyped(evt);
            }
        });

        search_btn.setText("chercher");
        search_btn.setBorder(null);
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(liste_employe)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(client_search, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(client_search, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(liste_employe))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Nom : ");

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero CIN : ");

        prename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenameActionPerformed(evt);
            }
        });
        prename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prenameKeyReleased(evt);
            }
        });

        jLabel3.setText("Prenom : ");

        jLabel4.setText("Telephone : ");

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });

        jLabel5.setText("Poste : ");

        poste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posteActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        photoImage.setText("Personal Image");
        photoImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qrcontain.setText("QR CODE Personal");
        qrcontain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setBackground(new java.awt.Color(51, 153, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Supprimer");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresseActionPerformed(evt);
            }
        });

        jLabel7.setText("Adresse : ");

        date_naissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_naissanceActionPerformed(evt);
            }
        });

        jLabel6.setText("Date de naissance : ");

        add_image.setText("Add");
        add_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_imageActionPerformed(evt);
            }
        });

        identifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identifiantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(photoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_image, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(qrcontain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(poste)
                    .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_naissance)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cin)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 277, Short.MAX_VALUE))
                            .addComponent(name)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(230, 230, 230)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(prename, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(adresse)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prename, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(date_naissance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poste, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(qrcontain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(photoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(add_image, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void client_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_searchActionPerformed

    private void client_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_client_searchKeyPressed

    }//GEN-LAST:event_client_searchKeyPressed

    private void client_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_client_searchKeyTyped
        String txtContent = client_search.getText();
        if ("cherche ici...".equals(txtContent)){
            client_search.setText("");
            client_search.setForeground(Color.BLACK);
        }
        if ("".equals(txtContent)){
            client_search.setText("cherche ici...");
            client_search.setForeground(Color.decode("#666666"));
        }
    }//GEN-LAST:event_client_searchKeyTyped

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        String content = client_search.getText();
        if (content==null || content.equals("") || content.equalsIgnoreCase("cherche ici...")){
            ChargerListe();
        }
        else{
            ChercheListe(content);
        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinActionPerformed

    private void prenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenameActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void posteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posteActionPerformed

    private void adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresseActionPerformed
    String s;
    
    private void add_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_imageActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if (result==JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            photoImage.setIcon(ResizeImage(path));
            s = path;
        }
    }//GEN-LAST:event_add_imageActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nom = name.getText();
        String prenom = this.prename.getText();
        String numCIN = this.cin.getText();
        String adresse = this.adresse.getText();
        String date_naisse = this.date_naissance.getText();
        String telephone = this.phone.getText();
        String poste = this.poste.getText();
        String path = s;
        
        try {
            Personne p1 = new Personne(nom, prenom, numCIN, date_naisse, poste,adresse,telephone,path);
            controlPersonne cp = new controlPersonne();
            cp.insert(p1);
            String identifiant = cp.takeLast();
            String chemin = generateQR(identifiant);
            cp.SetQR(chemin, identifiant);
            JOptionPane.showMessageDialog(this, "Ajout réussi!!");
            ChargerListe();
            resetAll();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(personnel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(personnel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void date_naissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_naissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_naissanceActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        
    }//GEN-LAST:event_nameKeyTyped

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed

    }//GEN-LAST:event_nameKeyPressed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        String content = name.getText();
        name.setText(content.toUpperCase());
    }//GEN-LAST:event_nameKeyReleased

    private void prenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenameKeyReleased
        String content = prename.getText();
        prename.setText(capitalize(content));
    }//GEN-LAST:event_prenameKeyReleased

    private void client_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_client_searchKeyReleased

    }//GEN-LAST:event_client_searchKeyReleased

    private void identifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identifiantActionPerformed

    private void liste_resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liste_resultMouseClicked
        int ligne = liste_result.getSelectedRow();
        String clientId = String.valueOf(liste_result.getValueAt(ligne, 0));
        
        try {
            controlPersonne cp = new controlPersonne();
            String client[] = cp.getPersonnal(clientId);
            // Set value of all Champs
            identifiant.setText(client[0]);
            name.setText(client[1]);
            prename.setText(client[2]);
            cin.setText(client[6]);
            adresse.setText(client[7]);
            date_naissance.setText(client[3]);
            phone.setText(client[5]);
            poste.setText(client[4]);
            
            qrcontain.setText("");
            ImageIcon qrcode = ResizeQR(client[8]);
            System.out.println(qrcode);
            qrcontain.setIcon(qrcode);
        } catch (Exception ex) {
            Logger.getLogger(personnel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_liste_resultMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nom = name.getText();
        String prenom = this.prename.getText();
        String numCIN = this.cin.getText();
        String adresse = this.adresse.getText();
        String date_naisse = this.date_naissance.getText();
        String telephone = this.phone.getText();
        String poste = this.poste.getText();
        String id = identifiant.getText();
        
        try {
            Personne p1 = new Personne(nom, prenom, numCIN, date_naisse, poste,adresse,telephone);
            controlPersonne cp = new controlPersonne();
            cp.update(id, p1);
            JOptionPane.showMessageDialog(this, "Mis a jours reussi!!!");
            resetAll();
        } catch (Exception ex) {
            Logger.getLogger(personnel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String id = identifiant.getText();
        try {
            controlPersonne cp = new controlPersonne();
            cp.virtualDelete(id);
            JOptionPane.showMessageDialog(this, "Deplace dans corbeille!");
            ChargerListe();
            resetAll();
        } catch (Exception ex) {
            Logger.getLogger(personnel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    public ImageIcon ResizeImage(String imagePath){
        ImageIcon myImage = new ImageIcon(imagePath);
        Image imge = myImage.getImage();
        Image newImage = imge.getScaledInstance(photoImage.getWidth(), photoImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    
    public ImageIcon ResizeQR(String imagePath){
        ImageIcon myImage = new javax.swing.ImageIcon(getClass().getResource(path));
        Image imge = myImage.getImage();
        Image newImage = imge.getScaledInstance(400, 400, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    
    public void ChargerListe() {
        String titre[] = {"id", "Nom", "Prénoms"};
        Object enreg[][] = new Object[1][1];

        try {
            controlPersonne cp = new controlPersonne();
            
            int nbr = cp.countEnreg();
            enreg = new Object[nbr][titre.length];
            ResultSet rs1 = cp.getAll();
            int i = 0;
            while (rs1.next()) {
                enreg[i][0] = (Object) rs1.getString("id");
                enreg[i][1] = (Object) rs1.getString("nom");
                enreg[i][2] = (Object) rs1.getString("prenom");
                i++;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        liste_result.setModel(new DefaultTableModel(enreg, titre));
        liste_employe.setViewportView(liste_result);
    }
    
    public void ChercheListe(String str){
        String titre[] = {"id", "Nom", "Prénoms"};
        Object enreg[][] = new Object[1][1];

        try {
            controlPersonne cp = new controlPersonne();
            
            int nbr = cp.countEnreg();
            enreg = new Object[nbr][titre.length];
            ResultSet rs1 = cp.searchAll(str);
            int i = 0;
            while (rs1.next()) {
                enreg[i][0] = (Object) rs1.getString("id");
                enreg[i][1] = (Object) rs1.getString("nom");
                enreg[i][2] = (Object) rs1.getString("prenom");
                i++;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        liste_result.setModel(new DefaultTableModel(enreg, titre));
        liste_employe.setViewportView(liste_result);
    }
    
    // Creations of reset function
    public void resetAll(){
        identifiant.setText("");
        name.setText("");
        prename.setText("");
        cin.setText("");
        adresse.setText("");
        date_naissance.setText("");
        phone.setText("");
        poste.setText("");
    }
   public String capitalize(String str){
       if (str==null || str.length()==0) return str;
       return str.substring(0,1).toUpperCase() + str.substring(1);
   }
   
   // GenerateQR code for client
   public String generateQR(String id){
    try{
             ByteArrayOutputStream out= QRCode.from(id).to(ImageType.PNG).stream();
             String fname = id;
             String path_name = "../Projet_JAVA/src/media/qrcode/";
             FileOutputStream fout;
             fout = new FileOutputStream(new File(path_name + (fname + ".PNG")));
             fout.write(out.toByteArray());
             fout.flush();
             System.out.println("Created SUccesfully....");
             return "/media/qrcode/" + id + ".PNG";
         }
         catch(Exception e){
             System.out.println(e);

         }
        return null;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_image;
    private javax.swing.JTextField adresse;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField client_search;
    private javax.swing.JTextField date_naissance;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField identifiant;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane liste_employe;
    private javax.swing.JTable liste_result;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel photoImage;
    private javax.swing.JTextField poste;
    private javax.swing.JTextField prename;
    private javax.swing.JLabel qrcontain;
    private javax.swing.JButton search_btn;
    // End of variables declaration//GEN-END:variables
}
